name: Continuous Integration and Delivery with Github Actions
on:
  push:
    branches:
      - "main"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v4
    
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN}}
        
    - name: Azure Container Registry Login
      uses: Azure/docker-login@v1
      with:
        username: ${{ secrets.AZ_DOCKER_USERNAME }}
        password: ${{ secrets.AZ_DOCKER_PASSWORD }}
        login-server: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
        
    - name: Setup Java 21
      uses: actions/setup-java@v2
      with:
        java-version: '21'
        distribution: 'adopt'
        cache: maven
        
    - name: Build Application .jar
      working-directory: ./09_ContinuousIntegrationWithAzure/rest-with-spring-boot-and-java-erudio
      run: mvn clean package
      
    - name: Docker Compose Build
      working-directory: ./09_ContinuousIntegrationWithAzure
      run: docker compose build
      
    - name: Tag and Push Docker Image to Azure Container Registry - ACR
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-erudio:latest ${{ secrets.AZURE_CONTAINER_REGISTRY }}/rest-with-spring-boot-erudio:latest
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-erudio:latest ${{ secrets.AZURE_CONTAINER_REGISTRY }}/rest-with-spring-boot-erudio:${{ github.run_id }}
        
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/rest-with-spring-boot-erudio:latest
        docker push ${{ secrets.AZURE_CONTAINER_REGISTRY }}/rest-with-spring-boot-erudio:${{ github.run_id }}
        
    - name: Azure Login
      uses: Azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        
    - name: Azure WebApp Container - Application Deployment
      uses: Azure/webapps-deploy@v2.2.10
      with:
        app-name: ${{ secrets.AZURE_APP_NAME }}
        images: ${{ secrets.AZURE_CONTAINER_REGISTRY }}/rest-with-spring-boot-erudio:${{ github.run_id }}
        
    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-erudio:latest ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-erudio:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-erudio:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot-erudio:${{ github.run_id }}